# Generated by Django 5.1.2 on 2024-10-31 11:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('correct_marks', models.IntegerField()),
                ('incorrect_marks', models.IntegerField()),
                ('difficulty_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='')),
                ('attempted_quiz', models.IntegerField()),
                ('created_quiz', models.IntegerField()),
                ('last_login_date', models.DateField()),
                ('rank', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by_admin', models.BooleanField()),
                ('max_marks', models.IntegerField()),
                ('max_time', models.IntegerField()),
                ('num_questions', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.category')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.participant')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField()),
                ('attempted_questions', models.IntegerField()),
                ('final_score', models.IntegerField()),
                ('quiz_rank', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.participant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='MainApp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question_text', models.CharField(max_length=500)),
                ('option1_text', models.CharField(max_length=500)),
                ('option2_text', models.CharField(max_length=500)),
                ('option3_text', models.CharField(max_length=500)),
                ('option4_text', models.CharField(max_length=500)),
                ('correct_option', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='MainApp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestionsAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_selected', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('marks', models.IntegerField()),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='MainApp.quizattempt')),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='MainApp.quizquestion')),
            ],
        ),
    ]
