# Generated by Django 5.1.2 on 2024-11-01 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterField(
            model_name='category',
            name='difficulty_level',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='attempted_quiz',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_quiz',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='participant',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_login_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='rank',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_by_admin',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='participant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.participant'),
        ),
    ]
