# Generated by Django 5.1.2 on 2024-11-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_category_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='attempted_quiz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_quiz',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
