# Generated by Django 5.1.2 on 2024-11-01 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_participant_age_alter_participant_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_by_admin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.participant'),
        ),
    ]
